### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anuragteapot** [Anu1601CS/media-manager#3]
- [ ] Multi adapter support

- [ ] Add Dropbox, Google Drive plugin

- [ ] Add Image editor

- [x] A rest full api for file serving
